spring:
  config:
    import: optional:file:./.env.properties

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/bd-api-financas}
    username: ${DB_USER:coti}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:coti}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2
          max-interval: 5s

integrations:
  agentes-ia:
    base-url: ${AGENTES_IA_BASE_URL:http://localhost:8084}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true